### ISSUE TITLE
Make implementing Binder optional

### ISSUE THREAD

**Issue by ribice** [go-chi/render#20]
Sometimes I don't need to validate anything in request.

Would you consider a PR where render.Bind accepts `r *http.Request, v interface{}`, and if `v` implements Bind() method only then execute it?

**Comment by strawb3rryx7** [comment]
Any news on that?

**Comment by fr3fou** [comment]
I was wondering the same thing! What did you end up doing?

**Comment by ribice** [comment]
I'm using gorilla for all my APIs and have this method written on my own.
