### ISSUE TITLE
Why use "reflect.Select()" instead of "select {}"?

### ISSUE THREAD

**Issue by ghostiam** [go-chi/render#25]
Hi. 
I would like to find out (for educational purposes) why "reflect.Select ()" is used instead of "select {}"?
I do not see any advantages using the "reflect" package. 

```go
...
switch chosen, recv, ok := reflect.Select([]reflect.SelectCase{
	{Dir: reflect.SelectRecv, Chan: reflect.ValueOf(ctx.Done())},
	{Dir: reflect.SelectRecv, Chan: reflect.ValueOf(v)},
}); chosen {
	case 0:
		...
	default:
		...
}
...
```
https://github.com/go-chi/render/blob/master/responder.go#L160-L163

vs 

```go
select {
	case <- ctx.Done():
		...
	case recv, ok <- v:
		...
}
```

**Comment by VojtechVitek** [comment]
Well, because we don't know type of the channel ahead.

Feel free to try to changing to `select {}` and provide a PR, but I suspect it won't be possible.
