### ISSUE TITLE
Why does render.JSON use Encoder rather than marshal?

### ISSUE THREAD

**Issue by Mentioum** [go-chi/render#27]
I was writing some unit tests for my http handlers and I came across a weird scenario where there was a new line `/n` char being added to the end of my JSON response (and hence my test failing when comparing the string responses).

On investigating it seems to be exected behaviour when using the the `json.NewEncoder(buf)`.  Apparently its useful for logging programs etc when you want to be able to ouput things to your terminal or a logging program and the newline is particularly useful, however I'm not sure why its being used here.

Could someome please explain to me why [this](https://github.com/go-chi/render/blob/3215478343fbc559bd3fc08f7031bb134d6bdad5/responder.go#L93) function uses `json.NewEncoder(buf)` rather than `json.Marshal(v interface{})` I'd really appreciate it.

Is it a performance reason?

**Comment by solderjs** [comment]
Not part of the project, but just came across your issue and I believe I can give you a satisfactory answer.

See https://golang.org/pkg/encoding/json/#NewEncoder

`json.Encoder` streams the data in chunks which, in theory, can allow it to keep memory pressure low.

As to why it puts a `\n`... I'm not sure. Personally, I appreciate an extra `\n`, but you might also consider `strings.TrimSpace()`: https://golang.org/pkg/strings/#TrimSpace

**Comment by VojtechVitek** [comment]
Correct. The json.Encoder is used to stream the JSON bytes directly to the ResponseWriter as soon as they're ready.

With render.JSON, it'd have to wait for a full response to be built in the buffer first before the first byte can be sent out to a client.

**Comment by VojtechVitek** [comment]
Actually, looking into the link, we're not really leveraging the streaming capability. We can improve that.

However, the encoder also enables some settings like enc.SetEscapeHTML(), which you don't get by default with json.Marshal.
